"""add function job tables

Revision ID: 950494a84fc4
Revises: 7519ff25ab31
Create Date: 2024-11-17 23:41:29.049049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '950494a84fc4'
down_revision = '7519ff25ab31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_job',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('param_object', sa.String(length=255), nullable=False),
    sa.Column('param_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_job_customer_id'), 'function_job', ['customer_id'], unique=False)
    op.create_table('function_job_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('param_object', sa.String(length=255), nullable=False),
    sa.Column('param_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_job_history_customer_id'), 'function_job_history', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_function_job_history_customer_id'), table_name='function_job_history')
    op.drop_table('function_job_history')
    op.drop_index(op.f('ix_function_job_customer_id'), table_name='function_job')
    op.drop_table('function_job')
    # ### end Alembic commands ###