"""add function job tables

Revision ID: 7519ff25ab31
Revises: be4462335562
Create Date: 2024-11-17 23:35:55.488292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7519ff25ab31'
down_revision = 'be4462335562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###