"""Initial migration

Revision ID: 69427947d8fe
Revises: 
Create Date: 2024-10-10 17:04:41.961613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69427947d8fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cin', sa.CHAR(length=7), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account', sa.CHAR(length=12), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', 'cin'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_customers_account'), 'customers', ['account'], unique=False)
    op.create_index(op.f('ix_customers_cin'), 'customers', ['cin'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('cin', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account', sa.CHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cin', name='users_pkey')
    )
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_cin'), table_name='customers')
    op.drop_index(op.f('ix_customers_account'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
